#!/usr/bin/env bash
########################################################################################################################
## Wrapper for Oracle's dms-db-prep-v2.sh
## Generates customized DMS preparation SQL scripts with:
##   - Migration-specific file names (no collisions between migrations)
##   - ACCEPT prompts for passwords (no passwords stored in files)
##
## Usage:
##   ./generate-prep-sql.sh --source --online --multitenant --pdb-service PEPE --identifier PEPE
##   ./generate-prep-sql.sh --target --online --adb --identifier ADB_PROD
##   ./generate-prep-sql.sh --help
##
## Output:
##   dms_prep_{source|target}_{IDENTIFIER}.sql   — Phase 1: validation (run on DB)
##   DMS_Configuration_{source|target}_{IDENTIFIER}.sql — Phase 2: generated by Phase 1 (remediation)
########################################################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORACLE_SCRIPT="${SCRIPT_DIR}/dms-db-prep-v2.sh"

# --- Defaults ---
DB_ROLE=""          # source | target
MIG_TYPE="online"   # online | offline
IS_RDS="n"
IS_ADB="n"
TENANCY="s"         # s(ingle) | m(ulti)
PDB_SERVICE=""
INITIAL_LOAD_USER="ggadmin"
USE_DEFAULT_REP_USER="y"
IDENTIFIER=""

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Required:
  --source | --target       Database role
  --identifier NAME         Migration identifier for file naming (e.g., PEPE, PROD_HR)

Database type (source only):
  --rds                     AWS RDS Oracle
  --adb                     Autonomous Database
  --multitenant             CDB+PDB architecture (default: single-tenant)
  --pdb-service NAME        PDB service name (required if --multitenant)

Migration:
  --online                  Online migration (default)
  --offline                 Offline migration
  --initial-load-user NAME  Initial load user (default: ggadmin for online, system for offline)

Examples:
  $(basename "$0") --source --online --multitenant --pdb-service PEPE --identifier PEPE
  $(basename "$0") --target --online --adb --identifier ADB_PROD
EOF
    exit 0
}

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)       DB_ROLE="s" ;;
        --target)       DB_ROLE="t" ;;
        --online)       MIG_TYPE="on" ;;
        --offline)      MIG_TYPE="off" ;;
        --rds)          IS_RDS="y" ;;
        --adb)          IS_ADB="y" ;;
        --multitenant)  TENANCY="m" ;;
        --pdb-service)  PDB_SERVICE="$2"; shift ;;
        --initial-load-user) INITIAL_LOAD_USER="$2"; shift ;;
        --identifier)   IDENTIFIER="$2"; shift ;;
        --help|-h)      usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
    shift
done

# --- Validate ---
if [[ -z "$DB_ROLE" ]]; then
    echo "ERROR: --source or --target is required"; exit 1
fi
if [[ -z "$IDENTIFIER" ]]; then
    echo "ERROR: --identifier is required"; exit 1
fi
if [[ "$TENANCY" == "m" && -z "$PDB_SERVICE" && "$DB_ROLE" == "s" ]]; then
    echo "ERROR: --pdb-service is required with --multitenant"; exit 1
fi

if [[ ! -f "$ORACLE_SCRIPT" ]]; then
    echo "ERROR: Oracle script not found at $ORACLE_SCRIPT"; exit 1
fi

# --- Determine role label ---
if [[ "$DB_ROLE" == "s" ]]; then
    ROLE_LABEL="source"
else
    ROLE_LABEL="target"
fi

# --- Build input sequence for Oracle's interactive script ---
build_inputs() {
    local inputs=""

    if [[ "$DB_ROLE" == "s" ]]; then
        # Source DB flow
        inputs+="s\n"                           # Database type: source
        inputs+="${IS_RDS}\n"                    # Is RDS?

        if [[ "$IS_RDS" == "n" ]]; then
            inputs+="${IS_ADB}\n"                # Is ADB?
            if [[ "$IS_ADB" == "n" ]]; then
                inputs+="${TENANCY}\n"           # Multi/single tenant
                if [[ "$TENANCY" == "m" ]]; then
                    inputs+="${PDB_SERVICE}\n"   # PDB service name
                fi
            fi
        fi

        inputs+="${MIG_TYPE}\n"                  # Migration type

        if [[ "$IS_RDS" == "n" ]]; then
            inputs+="${INITIAL_LOAD_USER}\n"     # Initial load user
            inputs+="DUMMY_PWD\n"                # Password (will be replaced)
        fi

        if [[ "$MIG_TYPE" == "on" ]]; then
            if [[ "$IS_ADB" == "y" ]]; then
                inputs+="\n"                     # Press Enter for ggadmin confirmation
                # Password prompt only if initial_load_user != ggadmin
                if [[ "${INITIAL_LOAD_USER,,}" != "ggadmin" ]]; then
                    inputs+="DUMMY_PWD\n"
                fi
            elif [[ "$TENANCY" == "m" ]]; then
                inputs+="y\n"                    # Use default ggadmin/c##ggadmin
                # Password reused if initial_load_user == ggadmin
                if [[ "${INITIAL_LOAD_USER,,}" != "ggadmin" ]]; then
                    inputs+="DUMMY_PWD\n"
                fi
            else
                inputs+="y\n"                    # Use default ggadmin
                if [[ "${INITIAL_LOAD_USER,,}" != "ggadmin" ]]; then
                    inputs+="DUMMY_PWD\n"
                fi
            fi
        fi

    else
        # Target DB flow
        inputs+="t\n"                            # Database type: target
        inputs+="${MIG_TYPE}\n"                   # Migration type
        inputs+="${IS_ADB}\n"                     # Is ADB?

        if [[ "$IS_ADB" == "y" ]]; then
            if [[ "$MIG_TYPE" == "on" ]]; then
                inputs+="DUMMY_PWD\n"            # ggadmin password
            fi
        else
            inputs+="${TENANCY}\n"               # Multi/single tenant
            if [[ "$TENANCY" == "m" ]]; then
                inputs+="${PDB_SERVICE}\n"        # PDB service name
            fi
            inputs+="${INITIAL_LOAD_USER}\n"     # Initial load user
            inputs+="DUMMY_PWD\n"                # Password
            if [[ "$MIG_TYPE" == "on" ]]; then
                inputs+="y\n"                    # Use default ggadmin
                if [[ "${INITIAL_LOAD_USER,,}" != "ggadmin" ]]; then
                    inputs+="DUMMY_PWD\n"
                fi
            fi
        fi
    fi

    printf "$inputs"
}

# --- Generate ---
echo "Generating DMS prep SQL for ${ROLE_LABEL} (${IDENTIFIER})..."

cd "$SCRIPT_DIR"

# Clean previous output
rm -f dms_prep_db.sql

# Run Oracle's script with piped inputs
build_inputs | bash "$ORACLE_SCRIPT" > /dev/null 2>&1

if [[ ! -f dms_prep_db.sql ]]; then
    echo "ERROR: Oracle script did not generate dms_prep_db.sql"
    exit 1
fi

# --- Post-process ---
OUTPUT_FILE="dms_prep_${ROLE_LABEL}_${IDENTIFIER}.sql"
SPOOL_FILE="DMS_Configuration_${ROLE_LABEL}_${IDENTIFIER}.sql"

mv dms_prep_db.sql "$OUTPUT_FILE"

# Replace spool filename
sed -i "s|DMS_Configuration\.sql|${SPOOL_FILE}|g" "$OUTPUT_FILE"

# Replace hardcoded passwords with ACCEPT substitution variables
# Add ACCEPT prompt before the spool line
sed -i "/^spool /i ACCEPT ggadmin_pwd CHAR PROMPT 'Enter password for GGADMIN: ' HIDE" "$OUTPUT_FILE"

# Replace DUMMY_PWD and 'dummy' password values with substitution variable
sed -i "s|'DUMMY_PWD'|'\&ggadmin_pwd'|g" "$OUTPUT_FILE"
sed -i "s|'dummy'|'\&ggadmin_pwd'|g" "$OUTPUT_FILE"

# Update file header
sed -i "s|File Name    : dms_prep_db.sql|File Name    : ${OUTPUT_FILE}|" "$OUTPUT_FILE"
sed -i "s|Call Syntax  : @dms_prep_db|Call Syntax  : @${OUTPUT_FILE%.sql}|" "$OUTPUT_FILE"
sed -i "s|Output file  : ${SPOOL_FILE}|Output file  : ${SPOOL_FILE}|" "$OUTPUT_FILE"

echo ""
echo "Generated: ${SCRIPT_DIR}/${OUTPUT_FILE}"
echo "  Run on DB as SYSDBA → generates: ${SPOOL_FILE}"
echo "  Review ${SPOOL_FILE}, then execute to apply changes."
